// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    [Table("Admin")]
    public partial class Admin
    {
        public Admin()
        {
            Exams = new HashSet<Exam>();
            Students = new HashSet<Student>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Pass { get; set; }

        [InverseProperty("Admin")]
        public virtual ICollection<Exam> Exams { get; set; }
        [InverseProperty("Admin")]
        public virtual ICollection<Student> Students { get; set; }
    }
}