// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    [Index("Q_ID", Name = "c3", IsUnique = true)]
    public partial class Answer
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        public int Q_ID { get; set; }

        [ForeignKey("Q_ID")]
        [InverseProperty("Answer")]
        public virtual Question Q_IDNavigation { get; set; }
    }
}