// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    public partial class Exam
    {
        public Exam()
        {
            Grades = new HashSet<Grade>();
            Questions = new HashSet<Question>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        public int? Admin_ID { get; set; }

        [ForeignKey("Admin_ID")]
        [InverseProperty("Exams")]
        public virtual Admin Admin { get; set; }
        [InverseProperty("Exam")]
        public virtual ICollection<Grade> Grades { get; set; }
        [InverseProperty("Exam")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}