// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    public partial class Grade
    {
        [Key]
        public int Exam_ID { get; set; }
        [Key]
        public int St_ID { get; set; }
        [Column("Grade")]
        public int? Grade1 { get; set; }

        [ForeignKey("Exam_ID")]
        [InverseProperty("Grades")]
        public virtual Exam Exam { get; set; }
        [ForeignKey("St_ID")]
        [InverseProperty("Grades")]
        public virtual Student St { get; set; }
    }
}