// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    public partial class Question
    {
        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        public int Exam_ID { get; set; }

        [ForeignKey("Exam_ID")]
        [InverseProperty("Questions")]
        public virtual Exam Exam { get; set; }
        [InverseProperty("Q_IDNavigation")]
        public virtual Answer Answer { get; set; }
    }
}