// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExamsSystem.Models
{
    public partial class Student
    {
        public Student()
        {
            Grades = new HashSet<Grade>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Pass { get; set; }
        public int? Admin_ID { get; set; }

        [ForeignKey("Admin_ID")]
        [InverseProperty("Students")]
        public virtual Admin Admin { get; set; }
        [InverseProperty("St")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}